[package]
name = "near-ibc"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "4.0.0"
ibc = { version = "0.28.0", default-features = false, features = ["parity-scale-codec", "mocks-no-std", "serde", "borsh"]}
ibc-proto = { version = "0.25.0", default-features = false }
sha2 = { version = "0.10.6", default-features = false }
itertools = "0.10.5"


[profile.release]
codegen-units = 1
# Tell `rustc` to optimize for small code size.
opt-level = "z"
lto = true
debug = false
panic = "abort"
# Opt into extra safety checks on arithmetic operations https://stackoverflow.com/a/64136471/249801
overflow-checks = true

[patch.crates-io]
ibc = { git = "https://github.com/octopus-network/ibc-rs.git", branch = "octopus-v0.28.0"}
ibc-proto = { git = "https://github.com/octopus-network/ibc-proto-rs.git", branch = "octopus-v0.25.0" }
