[workspace]
members = [
    "channel-escrow",
    "escrow-factory",
    "near-ibc",
    "token-factory",
    "wrapped-token",
]

[profile.release]
codegen-units = 1
# Tell `rustc` to optimize for small code size.
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true

[patch.crates-io]
ibc = { git = "https://github.com/octopus-network/ibc-rs.git", branch = "rivers/near-ibc"}
ibc-proto = { git = "https://github.com/octopus-network/ibc-proto-rs.git", branch = "octopus-v0.25.0" }
