[workspace]
members = [
    "near-ibc",
]

[patch.crates-io]
ibc = { git = "https://github.com/octopus-network/ibc-rs.git", branch = "rivers/near-ibc"}
ibc-proto = { git = "https://github.com/octopus-network/ibc-proto-rs.git", branch = "octopus-v0.25.0" }
