[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
near-sdk = "4.1.0"
near-contract-standards = "4.1.0"
ibc = { version = "0.42", default-features = false, features = ["borsh", "serde"]}
