[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
near-sdk = { workspace = true }
near-contract-standards = { workspace = true }
ibc = { workspace = true }
