[package]
name = "channel-escrow"
version = "1.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = { workspace = true }
near-contract-standards = { workspace = true }
ibc = { workspace = true }
hex = { workspace = true }
utils = { path = "../utils" }
